### ISSUE TITLE
Integrate travis ci and tests

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_wok_android#10]
Please integrate travis and other test tools for this project.

**Comment by ridmal** [comment]
I fork the loklak_work_android project and run the app in my local machine.And i modified the .travis.yml file and do some builds with travis.
 **What went wrong:
A problem occurred configuring project ':app'.
failed to find target with hash string 'android-23' in: /usr/local/android-sdk**
i got this error. . now i am finding a solution for that.

**Comment by abishekvashok** [comment]
I think #20 fixed it

**Comment by abishekvashok** [comment]
Since, we got #22, can we close this?

**Comment by abishekvashok** [comment]
@mariobehling ^^
