### ISSUE TITLE
Add 'Press again to exit...' 

### ISSUE THREAD

**Issue by arundhatigupta** [fossasia/loklak_wok_android#110]
Currently hitting the Back button once exits the Tweet Harvesting Activity. The user might end up hitting the Back button by mistake which would cause an unintentional exit from the app. Thus  it would be a better option to ask the user to hit the Back button twice to exit the app.

**Comment by riyasingh1004** [comment]
Hi , I am Riya. I am would like to work on this issue .

**Comment by riyasingh1004** [comment]
Hi ,I am Riya. I would like to work on this issue.

**Comment by riyasingh1004** [comment]
Can someone please review my commit
