### ISSUE TITLE
Updating Documentation

### ISSUE THREAD

**Issue by chiragw15** [fossasia/loklak_wok_android#23]
Thinking of adding following in readme.md file : 

- Instructions to set up project locally
- Road Map
- Communication
- Branch Policy
- Code Style
- Contribution Guidelines
- Some Screenshots of current app.

@mariobehling Is there anything else required to be added?

**Comment by SKrPl** [comment]
@chiragw15 Can I work on this?

**Comment by chiragw15** [comment]
Yes sure. Proceed :+1:
