### ISSUE TITLE
Add tweet search suggestion feature

### ISSUE THREAD

**Issue by SKrPl** [fossasia/loklak_wok_android#27]
As in twitter's app, there is a tweet search option, going to that option displays trending hashtags and topics in a RecyclerView. Display the trending tweet topics in a RecyclerView using Loklak's [suggest](http://loklak.org/api.html#suggest) API.

The sub-functionalities that are required:
- [x] Display suggestions in RecyclerView.
- [x] Clicking on the search icon in keyboard while using EditText, should navigate the user to TweetSearch activity (to be created later)
- [x] Store the fetched suggestions in Realm Database, for persistent data.
- [x] When user types in EditText, wait for 0.5 seconds and then search for matching suggestions
- [x] Add a swipe to refresh functionality.

**Related twitter app image**
![18926442_1893321190955272_859147295_o](https://cloud.githubusercontent.com/assets/12163892/26757239/b9a6732c-48d3-11e7-8f92-b190b6c9d80d.png)

**Comment by SKrPl** [comment]
I am working on this ( part of GSoC project).

**Comment by abishekvashok** [comment]
@mariobehling i think it's solved. Isn't it?
