### ISSUE TITLE
Need different Version

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_wok_android#3]
Cannot publish app. Error:

You need to use a different version code for your APK because you already have one with version code 1.

**Comment by todipratik** [comment]
@mariobehling Did you get this error while uploading the app on Google Play Store?
The version code is set to **1** currently in [gradle file](https://github.com/loklak/loklak_wok_android/blob/master/app/build.gradle). It needs to be incremented to **2**.

**Comment by mariobehling** [comment]
Please feel free to do it and build a new app. The upload into the corresponding folder. Thanks.

**Comment by sudheesh001** [comment]
Lets also try to use `git tag` functionality to make app releases :smile:
