### ISSUE TITLE
Update gradle, android studio gradle plugin target sdk and build tools to latest

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/loklak_wok_android#30]
Currently we have old versions most of which does not support new features like the new support libraries, instant run, faster build times etc.

**It should be updated as follows**
Gradle version: 2.3.2
Android studio gradle plugin version: 3.3
Traget sdk: 25
build tools: 25.0.3

_Note: Travis configuration(.travis.yml) should also be updated_

**Comment by abishekvashok** [comment]
Working on it.

**Comment by SKrPl** [comment]
@abishekvashok As part of https://github.com/fossasia/loklak_wok_android/issues/27 I have updated some of the files. Please review it there :smile: .

**Comment by abishekvashok** [comment]
@SkrPl pls see it.
