### ISSUE TITLE
Add tweet search feature

### ISSUE THREAD

**Issue by SKrPl** [fossasia/loklak_wok_android#33]
When a keyword is searched (using the *magnifying lens* icon in keyboard) in the EditText present in `SuggestFragment` or one of the suggested topic in RecyclerView is clicked, it should navigate to `SearchFragment`. 
- [x] Obtain the JSON data of the search using [search](https://www.loklak.org/api.html#search) and display it in RecyclerView.
- [x] Create a separate RecyclerView adapter to display multiple images in a tweet.
- [x] Show different categories of tweets using `filter` parameter of *search* API endpoint. Tweets to be shown using `TabLayout` and `ViewPager`.
- [ ] Add a floating action button that will redirect to TweetPosting activity (to be added later)

![device-2017-06-07-115715](https://user-images.githubusercontent.com/12163892/26865046-898ec89a-4b78-11e7-8eff-6818f7d0d5eb.png)

**Comment by SKrPl** [comment]
I am working on this (part of GSoC) project.

**Comment by mariobehling** [comment]
This is out of scope currently. Closing it therefore.
