### ISSUE TITLE
Substitute Processing implementation 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_wok_android#34]
Currently the app is build using Processing, which is not the best choice performance wise. Please propose and implement an alternative.

**Comment by chiragw15** [comment]
@mariobehling @SKrPl If you need design ideas or other feature ideas and implementation, you can also have a look at my [proposal](https://drive.google.com/file/d/0B6IO4qTKhVUCUjRBUWdSWV95ejA/view?usp=sharing). The UI mockups in the proposal are elegant and follows material design guidelines. It also contains proposal for alternative of processing.

**Comment by mariobehling** [comment]
@chiragw15 Thanks. @SKrPl Hope this helps you.

But not all features in the proposal are a priority now. For the beginning we need the app to support all JS scrapers. The main goal of loklak wok in the first step is to enable the phone to harvest.

**Comment by SKrPl** [comment]
Thanks @chiragw15 I will use it as a reference, it would be really helpful :smile: .

**Comment by SKrPl** [comment]
@mariobehling Can you please edit the issue with the following TODOs.
- [x] Add [LiquidCore](https://github.com/LiquidPlayer/LiquidCore) to the project. Transpile and bundle the *Twitter JS scraper* and modify the transpiled and bundled file to respond to LiquidCore events.
- [x] Fetch search suggestions periodically by using [suggest](http://loklak.org/api.html#suggest) API and scrape tweets from the obtained queries using LiquidCore and bundled *Twitter JS scraper*.
- [x] Display the scraped tweets in *native Android widget (RecyclerView can be used)*.
- [x] Push the scraped tweets to Loklak Server using [push](http://loklak.org/api.html#push) API.
- [x] Remove already displayed tweets from the RecyclerView, if not removed it will crash the app (MemoryError).
