### ISSUE TITLE
Making Github releases instead of pushing APK to new branch

### ISSUE THREAD

**Issue by singhpratyush** [fossasia/loklak_wok_android#36]
As of now, the newly built APKs are pushed to a separate branch. It would be better to have Github releases for this purpose.

@SKrPl @hemantjadon @mariobehling: Views?

**Comment by abishekvashok** [comment]
Basically fossasia practises from the time I came here to push apks to a seperate branch and ensure continuous deliveries from there. Github Releases would push out milestonic releases like v0.1 alpha etc. We cannot have links to latest apks constant if we push out releases each and every time. IMO, we are polluting the github releases if we do so. If we skip app generation latest development apks would not be easily available, so I opt to stay the current manner on how it's carried out.

**Comment by singhpratyush** [comment]
@abishekvashok: I think you are right. The releases would be polluted by this. It is best to make releases manually in this case.

Thanks for the explanation.

**Comment by abishekvashok** [comment]
@singhpratyush sure.
