### ISSUE TITLE
No .editorconfig file for project

### ISSUE THREAD

**Issue by singhpratyush** [fossasia/loklak_wok_android#43]
The `.editorconfig ` file helps ensure consistency of code across various developers. Introducing it in the project would be a good idea.

See http://editorconfig.org/ for more.

**Comment by abishekvashok** [comment]
How is this one

```
# EditorConfig is awesome: http://EditorConfig.org

# EditorConfig helps developers define and maintain consistent coding styles
# between different editors and IDEs. The EditorConfig project consists of a
# file format for defining coding styles and a collection of text editor plugins
# that enable editors to read the file format and adhere to defined styles.
# EditorConfig files are easily readable and they work nicely with version
# control systems.

# top-most EditorConfig file
root = true

[*]
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

[*.java]
indent_style = space
indent_size = 4
```

And enable editorconfig in android-studio  -> Settings -> Editor -> Code & Style -> EditorConfig.

**Comment by singhpratyush** [comment]
@abishekvashok: We would also need configurations for XML files.

**Comment by abishekvashok** [comment]
@singhpratyush i don't think we need a precise ones for XML, [*] defines rules that are applied for all files. Do you feel we need to overwrite any?

**Comment by singhpratyush** [comment]
@abishekvashok: Yes, that would do.

**Comment by abishekvashok** [comment]
@singhpratyush can I add this?

**Comment by singhpratyush** [comment]
@abishekvashok: Sure. Please proceed.

**Comment by neelanshsahai** [comment]
@singhpratyush I am working on this now
