### ISSUE TITLE
Revert back package name to "org.loklak.android"

### ISSUE THREAD

**Issue by SKrPl** [fossasia/loklak_wok_android#78]
For beta release of the app:
- [ ] Revert back the current package name to `org.loklak.android`, change the `ui` subpackage to `wok` and `applicationId` to `org.loklak.android.wok` in `app/build.gradle` file.
- [ ] Add screenshot for splash screen.

**Comment by mittalprince** [comment]
sir may i work on this issue

**Comment by SKrPl** [comment]
@mittalprince Please go ahead 😄

**Comment by mittalprince** [comment]
sir i'm beginner in this field . so please you may tell me where the package is mentioned.
I have changed the application id .

**Comment by mittalprince** [comment]
sir one more question 
would i have to change the package name in all files where it is mentioned
please reply sir @SKrPl 
thanks

**Comment by SKrPl** [comment]
@mittalprince Please use refactoring to change the package name. Google about it.

**Comment by vibhcool** [comment]
@mittalprince , please don't use `sir`. It doesn't appears nice in open-source.  :)

**Comment by mittalprince** [comment]
k , i will see it

**Comment by passiondroid** [comment]
@mittalprince - Are you working on this issue ? If not then please let me know i can finish it.

**Comment by mittalprince** [comment]
@passiondroid , yes i'm working

**Comment by SKrPl** [comment]
@mittalprince Any updates on this ?

**Comment by iamareebjamal** [comment]
Yes please, we need `org.loklak.android.wok` to be the package name for automatic publishing :smile:
