### ISSUE TITLE
Harvest tweet card UI

### ISSUE THREAD

**Issue by anandwana001** [fossasia/loklak_wok_android#83]
I would like to work on the cardView of this screen!!
 
![tweetharvesting](https://user-images.githubusercontent.com/25057618/31410990-df247710-ae2d-11e7-8adf-0fd03798d3f2.png)

**Comment by singhpratyush** [comment]
Hi @anandwana001! What would you change this to? Do you have some illustrations/mockups?

**Comment by anandwana001** [comment]
![image](https://user-images.githubusercontent.com/25057618/31580974-1cd9291a-b17c-11e7-91d2-1a8e5878c928.png)
image from loklak wok twitter page. @singhpratyush give your feedback

**Comment by anandwana001** [comment]
How about this!! 
![screenshot_2017-10-15-13-20-21-771_org loklak wok](https://user-images.githubusercontent.com/25057618/31582832-c6055638-b1ab-11e7-99f5-7c25b5abde6b.png)

**Comment by anandwana001** [comment]
@singhpratyush as you had suggested about the username color, no single quote will be there around twitter handler, here you can review and I'll make one PR for this.
![image](https://user-images.githubusercontent.com/25057618/32034237-0bf30e0c-ba2f-11e7-8492-4e400bc5d998.png)
