### ISSUE TITLE
Automatically build an apk file in the apk branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_wok_android#9]
The goal of this issue is to get an apk on each merged pull request build in the apk branch.

Use travis to build apks automatically. You can check other FOSSASIA projects e.g. Open Event Android and Susi Android how it is done there.

**Comment by abishekvashok** [comment]
I would like to work on it @mariobehling

**Comment by mariobehling** [comment]
Not working yet, as travis is still failing.

**Comment by abishekvashok** [comment]
@mariobehling as I mentioned in the PR it's not working and Travis is failing because the gradle commands are returning errors! We gotta fix them, this issue is done sir. (Remember to do as asked in the task mentioned in the PR) 👍

**Comment by abishekvashok** [comment]
I would fix gradle failing tests.

**Comment by abishekvashok** [comment]
The apk branch would also need a tweak, i will do it asap. I couldn't do it in the last pr as the branches were different.
