### ISSUE TITLE
Wrong placement of twitter fab button in search activity

### ISSUE THREAD

**Issue by S2606** [fossasia/loklak_wok_android#92]
![screenshot-1512316646600](https://user-images.githubusercontent.com/18497513/33527103-ee0de546-d870-11e7-9241-ac81a07c31a0.jpg)

**Comment by S2606** [comment]
I would like to work on this

**Comment by S2606** [comment]
Also a suggestion for no need of this fab button in search activity.Please do reply on this

**Comment by SKrPl** [comment]
@S2606 Please proceed 😄 . IMO Adding Fab button in `SearchFragment` makes the navigation easier to `TweetPostingFragment`, the user doesn't have to comeback to `SuggestFragment`.
